### ISSUE TITLE
Read messages from an external file.

### ISSUE THREAD

**Issue by sgdc3** [Kakifrucht/WorldGuardFix#9]

**Comment by sgdc3** [comment]
or maybe from worldguard directly

**Comment by Kakifrucht** [comment]
You mean to configure the messages? Afaik there is no way to edit them in WorldGuard either.

**Comment by sgdc3** [comment]
fair enough xD sorry, i forgot about it

**Comment by Kakifrucht** [comment]
Yeah, that would be nice but there is no way of doing that really.
